### ISSUE TITLE
MythicMobs/Crucible items not craftable with AutoCrafters

### ISSUE THREAD

**Issue by LcorpOfficial** [Aeltumn/automated_crafting#23]
**Describe the bug**
Items created in Mythicmobs/Crucible are not capable of being crafted with autocrafters, even though it uses WolfyScript's CustomCrafting to make them.
**To Reproduce**
1. Create an item with mythicmobs
2. set up a crafting recipe with CustomCrafting
3. try to use it on an autocrafter and receive this error:

**Expected behavior**
Autocrafter should match the itemstack and accept the recipe to craft

**Screenshots**
error
![image](https://user-images.githubusercontent.com/73314328/122680313-7ca24c00-d1bc-11eb-8e24-f2105cbb5b23.png)
CustomCrafting recipe
![image](https://user-images.githubusercontent.com/73314328/122680343-a3f91900-d1bc-11eb-89ff-755219bd5424.png)
item lore text formatting
![image](https://user-images.githubusercontent.com/73314328/122680575-db1bfa00-d1bd-11eb-91cb-c01496073859.png)

**Version Information**
What Minecraft/Bukkit version are you running?
This server is running Airplane version git-Airplane-"a13c511" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
What version of Automated Crafting are you using?
2.4
What versions of dependencies (like CustomCrafting) are being used?
CustomCrafting 1.6.6.0, MythicMobs 4.11.0

**Additional context**
MythicMobs links skills and attributes using NBT tags, and there is formatting to the name and lore text on the item.

**Comment by Aeltumn** [comment]
There is an incompatibility issue with CustomCrafting 1.6.6.0 at the moment that will be addressed in the next update, can you confirm that in your set up CustomCrafting is properly working and there aren't any console errors that indicate this issue is an incompatibility with the version of CustomCrafting rather than an issue specifically with MythicMobs?

**Comment by LcorpOfficial** [comment]
i can confirm it works for vanilla items just fine, upon closer inspection I did see this error, however. I think it could be related?

https://pastebin.com/9nK5BvZ2

**Comment by LcorpOfficial** [comment]
also noticed 2.5 only works on 1.17 currently, but it does seem to have the bugfix handled; will there be a working patch for 1.16 as well?

**Comment by Aeltumn** [comment]
That exception is because you're using a too new version of CustomCrafting, so it's not anything to do with MythicMobs. Simply use CustomCraft v1.6.1.0 instead. I will not be backporting the new update, 1.17 made significant changes where it makes it much harder to have backwards support. So, I decided to only support the latest version as a fully working older version is still available for the older MC versions. It does mean you'll have to use an old CustomCrafting version until you update.

**Comment by LcorpOfficial** [comment]
interesting, that works for me, for now at least.
